# Generated by Django 5.2.6 on 2025-10-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('fecha_matricula', models.DateField()),
            ],
        ),
    ]
