# Generated by Django 5.2.8 on 2025-12-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(default='disponible', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_herramienta',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramienta_codigo', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=200)),
                ('persona_entrega', models.CharField(blank=True, max_length=200)),
                ('persona_recibe', models.CharField(blank=True, max_length=200)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_prevista', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_prestamo',
                'ordering': ['-created_at'],
            },
        ),
    ]
