# Generated by Django 5.2.8 on 2025-12-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herramienta',
            options={},
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='tipo',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestada', 'Prestada')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='herramienta',
            table=None,
        ),
    ]
